version: '3.8'
name: ann-benchmarks-marklogic

services:

  marklogic:
    image: "ml-docker-db-dev-tierpoint.bed-artifactory.bedford.progress.com/marklogic/marklogic-server-centos:12.0.nightly-centos-1.1.2"
    platform: linux/amd64
    environment:
      - INSTALL_CONVERTERS=false
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - /var/opt/MarkLogic:/home/app/marklogic
    ports:
      - 7997-7999:7997-7999
      - 8000-8002:8000-8002
      - 8030:8030
